### PR TITLE
Finger names etc

### PR DESCRIPTION
**Pull request by T-vK**
Remember #3 from way back? I think the only problem was that I couldn't figure out how to calculate the height of a character. Fortunately the width of the character 'M' is extremely close to the real height of a number character so I went ahead and added a Height property to the object returned by MeasureString function. 

I think it looks pretty good now:
image

### CODE REVIEW

**Comment by acspike** [comment]
Awesome!

**Comment by mwcm** [comment]
did you look at the double-digit fret issue? still having trouble with that, going to try to fix that

**Comment by T-vK** [comment]
@mwcm For the double digit issue we'd have to change the convention of the `positions` attribute as it's currently expected to have 6 non-separated single digits. Ideally we'd keep backwards-compatibility by still allowing stuff like `positions="320003"`, but then also allow using a separator like this `positions="3 2 0 0 0 3"` and `positions="9 11 11 10 9 9"`.

**Comment by mwcm** [comment]
@T-vK  thanks for the quick reply! just finished going through the script, like you said it expects 6 non separated digits wherever position is mentioned. for sure, don't want to break anything

going to take another look tomorrow afternoon

**Comment by mwcm** [comment]
ended up combining [VexChords](https://github.com/0xfe/vexchords) with ChordJS [here](https://github.com/mwcm/ChordSVG), added the space separated positions as an option

**Comment by T-vK** [comment]
Cool, are there other improvements besides the space separated positioning?

**Comment by mwcm** [comment]
Yeah there are a couple changes, thanks for asking! 

The code structure is based on ChordJS, but the drawing is all based on the Vexchords SVG rendering, which means that nearly all the [Vexchords customizations](https://github.com/0xfe/vexchords#usage) work in ChordSVG (save Barre chords, still deciding how to go about it)

Also changed a couple things for my use case:
- the # of shown frets is auto adjusted based on the frets used in the `positions` array
- reworked the Vexchord `position` variable to be interpreted from the `positions` array
- added chord name drawing to Vexchords

Still have a couple TODO's and things to revise, but it's functioning for my purposes now!

**Pull request merged**
